# Generated by Django 5.0.6 on 2024-05-18 19:02

import django.core.validators
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(help_text='این فیلد برای احراز هویت استفاده میشود، در انتخاب آن دقت کنید', max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a]*$', message='تنها اعداد پذیرفته میشوند')], verbose_name='شماره تماس')),
                ('username', models.CharField(max_length=11, unique=True, verbose_name='نام کاربری')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعالیت')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی ادمین')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر')),
                ('joined_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'managed': True,
            },
        ),
    ]
