# Generated by Django 5.0.6 on 2024-11-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_at',
        ),
    ]
